# Uncomment the next line to define a global platform for your project
#
platform :ios, '12.0'

target 'iFeed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for iFeed
  pod 'FeedKit'
  pod 'Firebase/Crashlytics'

  target 'iFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


# Fix warnings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
