# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'iFeed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for iFeed
  
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'FeedKit'

  target 'iFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
